config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :hearts, only: :create
  get 'about' => 'pages#about'
  root 'pages#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/heart.rb
class Heart < ApplicationRecord
	belongs_to :post
	validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :hearts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController
	def create
	@heart = Heart.new(heart_params)

		if @heart.save
		    redirect_to @heart.post, notice: 'Hearted that post!'
		else
		    redirect_to root_url, notice: "Had an issue creating that heart"
		end
	end

	private
	# Never trust parameters from the scary internet, only allow the white list through.
    def heart_params
      params.require(:heart).permit(:post_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def welcome
  	@posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :kind, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <div class="page-header">
        <ul class="nav nav-pills pull-right">
          <li role= "presentation"><%= link_to "Home", root_url %></li>
          <li role= "presentation"><%= link_to "Manage Posts", posts_url %></li>
          <li role= "presentation"><%= link_to "About", about_url %></li>
        </ul>

        <h1>
          <%= link_to 'Myapp', "/" %>
          <small>// Destiny 2 dedicated app</small>
        </h1>
      </div>

      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>This app was build by Dan on <%= link_to "Ruby on Rails", "https://rubygarage.github.io/" %></p>

app/views/pages/welcome.html.erb
<% @posts.each do |post| %>
	<%= render 'posts/post', post: post %>
	<br><br><br><br>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :kind %>
    <%= form.select :kind, ["text", "image"], {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-group">
        <%= form.submit "Submit", class: 'btn btn-info btn-block' %>
      </div>
    </div>
  </div>

  
<% end %>

app/views/posts/_post.html.erb
<p>
  <h2>
  	<div class="pull-right">
  		<%= form_for(Heart.new) do |f| %>
  		<%= f.hidden_field :post_id, value: post.id %>
  		<%= f.submit "❤", class: 'btn btn-danger' %>
  		<% end %>
  	</div>
  	<%= link_to post.title, post %>
  </h2>
</p>

<p class="text-muted">
	<small>
		Posted on <%= post.created_at.to_formatted_s(:long) %>
	</small>
	<small class="pull-right">
		<%= post.hearts.count %> hearts
	</small>
</p>

<p>
	<% if post.kind == "image" %>
		<%= image_tag post.content, style: "width: 100%" %>
	<% else %>
		<%= simple_format post.content %>
	<% end %>
</p>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= truncate(post.content, length:70) %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% if notice.present? %>
  <p class="alert alert-success">
   <%= notice %>
  </p>
<% end %>	

<%= render 'post', post: @post %>

<%= link_to 'Back', posts_path %>